- hosts: all
  become: true
  tasks:
    - name: create a new deployment
      command: kubectl apply -f /home/ubuntu/Projects/Kubernetes-Production-Level-Project/K8S/deployment.yml
    - name: create a new service
      command: kubectl apply -f /home/ubuntu/Projects/Kubernetes-Production-Level-Project/K8S/service.yml 
