apiVersion: v1
kind: Service
metadata:
  name: k8sprod-project
  labels:
    app: k8sprod-project
spec:
  selector:
    app: k8sprod-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200  # Choose a port within the range 30000-32767

