apiVersion: v1
kind: Service
metadata:
  name: k8sprod-project-service
spec:
  selector:
    app: k8sprod-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Choose a port within the range 30000-32767

